### PR TITLE
Support skins with a second layer

### PR DESCRIPTION
**Pull request by CortexPE**
Title says it all 😉

### CODE REVIEW

**Comment by Muqsit** [comment]
But what's the logic behind it any why another y-loop?
The `rgbToTextFormat()` is heavy already, this could take a long time to process now that there are two 2-dimensional loops calling functions heavily.

**Comment by legoboy0215** [comment]
I agree. There is no point of another y-loop.

**Comment by Thunder33345** [comment]
like if there's front use the front and skip the background?

**Comment by CortexPE** [comment]
Is it better now?

~ Be back tomorrow.

**Pull request merged**
